Ambitious Champagne Mink

High

# Wrong ltoken given in function parameter

### Summary

When calling `liquidateCrossChain()` from chain B, the liquidator should give a parameter of `lTokenToSeize`, but it is transformed to ltoken on chain A in the later function `_executeLiquidationCore()` and never changed back. When chain B receive the message back, it could not get a correct ltoken back and leads to revert on both liquidation fail or success.

### Root Cause

Assume Alice have collateral of tokenA and other tokens on chain A and the corresponding token on chain B is tokenB. She cross-chain borrowed some tokenB on chain B but now she's collateral is not enough.

Bob wants to cross-chain liquidate Alice and he call `liquidateCrossChain(Alice,amount,idAï¼ŒlTokenB,tokenB)`. However, in the function below, lTokenB is changed to lTokenA by ` lendStorage.crossChainLTokenMap()`.

    function _executeLiquidationCore(LendStorage.LiquidationParams memory params) private {
        // Calculate seize tokens
        address borrowedlToken = lendStorage.underlyingTolToken(params.borrowedAsset);


        (uint256 amountSeizeError, uint256 seizeTokens) = LendtrollerInterfaceV2(lendtroller)
            .liquidateCalculateSeizeTokens(borrowedlToken, params.lTokenToSeize, params.repayAmount);


        require(amountSeizeError == 0, "Seize calculation failed");


        // Send message to Chain A to execute the seize
        _send(
            params.srcEid,
            seizeTokens,
            params.storedBorrowIndex,
            0,
            params.borrower,
            lendStorage.crossChainLTokenMap(params.lTokenToSeize, params.srcEid), // Convert to Chain A version before sending
            msg.sender,
            params.borrowedAsset,
            ContractType.CrossChainLiquidationExecute
        );
    }


After the process on chain A is done, the message sent back to chain B is still with parameter lTokenA. In both `_handleLiquidationSuccess()` or `_handleLiquidationFailure()` below, they call `lendStorage.lTokenToUnderlying(lTokenA)`. However, lTokenA is not a correct address on chain B, the `lTokenToUnderlying` maps it to `address(0)`, which leads to revert in both function.

https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CrossChainRouter.sol#L443C4-L482C77

### Internal Pre-conditions

none

### External Pre-conditions

none

### Attack Path

none

### Impact

The cross-chain liquidation process will not finish and the protocol lost money.

### PoC

_No response_

### Mitigation

_No response_